name: example
description: Example app using offline_first_sync_drift.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  offline_first_sync_drift:
    path: ../packages/offline_first_sync_drift
  offline_first_sync_drift_rest:
    path: ../packages/offline_first_sync_drift_rest
  drift: ^2.27.0
  sqlite3_flutter_libs: ^0.5.31
  path: ^1.9.1
  json_annotation: ^4.9.0

dev_dependencies:
  drift_dev: ^2.27.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  test: ^1.25.15
