name: offline_first_sync_drift
description: Core synchronization library with conflict resolution.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  drift: ^2.26.1

dev_dependencies:
  build_runner: ^2.4.15
  drift_dev: ^2.26.1
  test: ^1.25.15
